/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/markets': typeof ApiMarketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/markets': typeof ApiMarketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/markets': typeof ApiMarketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/markets' | '/trade' | '/wallet' | '/api/markets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/markets' | '/trade' | '/wallet' | '/api/markets'
  id: '__root__' | '/' | '/markets' | '/trade' | '/wallet' | '/api/markets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  ApiMarketsRoute: ApiMarketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
