/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as ApiPublicNotifyRouteImport } from './routes/api/public/notify'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyRoute = ApiPublicNotifyRouteImport.update({
  id: '/api/public/notify',
  path: '/api/public/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/markets'
    | '/news'
    | '/trade'
    | '/wallet'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/public/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/markets'
    | '/news'
    | '/trade'
    | '/wallet'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/public/notify'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/markets'
    | '/news'
    | '/trade'
    | '/wallet'
    | '/api/balance'
    | '/api/markets'
    | '/api/news'
    | '/api/public/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiPublicNotifyRoute: typeof ApiPublicNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify': {
      id: '/api/public/notify'
      path: '/api/public/notify'
      fullPath: '/api/public/notify'
      preLoaderRoute: typeof ApiPublicNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiPublicNotifyRoute: ApiPublicNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
